# -----------------------------
# Material Theme Configuration
# ------------------------------
# red, pink, purple, deep purple, indigo, 
# blue, light blue, cyan, teal, green, light green, 
# lime, yellow, amber, orange, deep orange, brown, 
# grey, blue grey , black, white
#    primary: pink # teal
#    accent: indigo
#
# *** FONT ***
# Guide: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
# Google Fonts Supported: https://fonts.google.com/
#
# *** BLOG ***
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
# ---------------------------------

# Project Information .........................................
site_name: "Retail Solution Accelerator - Workshop Guide"
site_url: https://emumbaorg.github.io/docs-retail-solution-accelerator
site_author: emumbaorg
site_description: >
  This guide serves as documentation for the deployment and configuration of retail solution accelerator.

# Repository Information ......................................
repo_name: emumbaorg/retail-solution-accelerator
repo_url: https://github.com/emumbaorg/docs-retail-solution-accelerator

# Copyright ...................................................
copyright: >
  Copyright &copy; 2025 - present Microsoft

# Theme Configuration .........................................
theme:
  name: material
  custom_dir: overrides  # (Optional) For further customizations via overrides
  logo: ./img/postgresql.svg
  favicon: ./img/postgresql.svg
  language: en

  # Typography: Using modern, clean fonts for readability
  font: # Monospaced regular
    text: Roboto
    code: Roboto Mono

  # Enhanced Professional Color Palette (Microsoft-inspired)
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Light mode: clean and minimal with blue-grey and accent gold
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode: deep slate with accent light blue for contrast
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#0078D4"       # Microsoft Blue
      accent: "#F3F2F1"        # Light accent for contrast
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  # Navigation and Layout Enhancements
  features:
    - navigation.instant
    - navigation.expand           # Collapsible sections in sidebar
    - navigation.instant.progress # Loading progress indicator
    - navigation.tracking         # Updates URL with section anchors
    - navigation.tabs             # Tabbed navigation on desktop
    - navigation.tabs.sticky      # Sticky tabs while scrolling
    - navigation.path             # Breadcrumbs for hierarchical context
    - navigation.indexes          # Use index.md as section landing page
    - navigation.top              # Back-to-top button for long pages
    - toc.follow                  # Table of contents follows scroll position
    - navigation.footer           # Consistent footer for additional links
    - content.code.copy           # Copy code snippets easily
    - content.tabs.link           # Synchronize tabs across pages

# Extra Configuration .........................................
extra:
  generator: false

# Plugins .......................................................
plugins:
  - search

# Markdown Extensions .........................................
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

# Navigation Structure .........................................
nav:
